export const charactersData = [
    {
        "characterClassName": "소서리스",
        "characterImage": "https://img.lostark.co.kr/armory/8/9b4bf59f3f625540f349e3d285b49fb71f7d4892603d7a11ea815edc78feb35a.png?v=20240215121242",
        "characterName": "마볼링",
        "itemLevel": 1624.17,
        "serverName": "루페온",
        "chaosCheck": 2,
        "guardianCheck": 0,
        "guardianGauge": 100,
        "todoList": [
            {
                "id": 320009,
                "name": "일리아칸<br />하드 1 2 3",
                "gold": 10000,
                "check": true,
                "message": null,
                "currentGate": 0,
                "totalGate": 3,
                "weekCategory": "일리아칸",
                "weekContentCategory": "하드",
                "sortNumber": 1,
                "goldCheck": true
            },
            {
                "id": 419599,
                "name": "카멘<br />노말 1 2",
                "gold": 7500,
                "check": true,
                "message": null,
                "currentGate": 0,
                "totalGate": 2,
                "weekCategory": "카멘",
                "weekContentCategory": "노말",
                "sortNumber": 2,
                "goldCheck": false
            },
            {
                "id": 220847,
                "name": "상아탑<br />노말 1 2 3 4",
                "gold": 9000,
                "check": true,
                "message": null,
                "currentGate": 0,
                "totalGate": 4,
                "weekCategory": "상아탑",
                "weekContentCategory": "노말",
                "sortNumber": 3,
                "goldCheck": true
            }
        ],
        "goldCharacter": true,
        "challengeGuardian": false,
        "challengeAbyss": false,
        "settings": {
            "showCharacter": true,
            "showEpona": false,
            "showChaos": true,
            "showGuardian": true,
            "showWeekTodo": true,
            "showWeekEpona": true,
            "showSilmaelChange": false,
            "showCubeTicket": true,
            "goldCheckVersion": false
        },
        "weekGold": 0,
        "weekEpona": 0,
        "silmaelChange": false,
        "cubeTicket": 2
    },
    {
        "id": 19232,
        "characterClassName": "소울이터",
        "characterImage": "https://img.lostark.co.kr/armory/6/279a31a947885c89933f3144bff34284875f6c3e65b8befbbdf660086fa47584.png?v=20240215120401",
        "characterName": "소울볼링",
        "itemLevel": 1600.0,
        "serverName": "루페온",
        "sortNumber": 1,
        "chaosName": null,
        "chaos": {
            "id": 9,
            "category": "카오스던전",
            "name": "천공2",
            "level": 1600.0,
            "shilling": 84164.0,
            "honorShard": 10128.0,
            "leapStone": 4.0,
            "destructionStone": 45.0,
            "guardianStone": 128.9,
            "jewelry": 11.0
        },
        "chaosCheck": 0,
        "chaosGauge": 0,
        "chaosGold": 617.34,
        "guardianName": null,
        "guardian": {
            "id": 15,
            "category": "가디언토벌",
            "name": "소나벨",
            "level": 1580.0,
            "shilling": 0.0,
            "honorShard": 0.0,
            "leapStone": 8.0,
            "destructionStone": 66.3,
            "guardianStone": 199.7,
            "jewelry": 0.0
        },
        "guardianCheck": 0,
        "guardianGauge": 100,
        "guardianGold": 891.98,
        "eponaCheck": 0,
        "eponaGauge": 100,
        "todoList": [
            {
                "id": 56618,
                "name": "카양겔<br />하드 1 2 3",
                "gold": 6500,
                "check": false,
                "message": null,
                "currentGate": 0,
                "totalGate": 3,
                "weekCategory": "카양겔",
                "weekContentCategory": "하드",
                "sortNumber": 1,
                "goldCheck": true
            },
            {
                "id": 317210,
                "name": "일리아칸<br />노말 1 2 3",
                "gold": 7500,
                "check": false,
                "message": null,
                "currentGate": 0,
                "totalGate": 3,
                "weekCategory": "일리아칸",
                "weekContentCategory": "노말",
                "sortNumber": 2,
                "goldCheck": true
            },
            {
                "id": 320040,
                "name": "아브렐슈드<br />하드 1 2",
                "gold": 4000,
                "check": false,
                "message": null,
                "currentGate": 0,
                "totalGate": 2,
                "weekCategory": "아브렐슈드",
                "weekContentCategory": "하드",
                "sortNumber": 999,
                "goldCheck": true
            }
        ],
        "goldCharacter": true,
        "challengeGuardian": false,
        "challengeAbyss": false,
        "settings": {
            "showCharacter": true,
            "showEpona": false,
            "showChaos": true,
            "showGuardian": true,
            "showWeekTodo": true,
            "showWeekEpona": true,
            "showSilmaelChange": false,
            "showCubeTicket": true,
            "goldCheckVersion": false
        },
        "weekGold": 0,
        "weekEpona": 0,
        "silmaelChange": false,
        "cubeTicket": 2
    },
    {
        "id": 19227,
        "characterClassName": "슬레이어",
        "characterImage": "https://img.lostark.co.kr/armory/0/6cd90515f70d8a55ed34a294a6a65b1ea56fc8ea0ae83aaa32986a7c33acae5f.png?v=20240215112743",
        "characterName": "가을볼링",
        "itemLevel": 1586.67,
        "serverName": "루페온",
        "sortNumber": 2,
        "chaosName": null,
        "chaos": {
            "id": 8,
            "category": "카오스던전",
            "name": "천공1",
            "level": 1580.0,
            "shilling": 80164.0,
            "honorShard": 9913.0,
            "leapStone": 3.1,
            "destructionStone": 39.9,
            "guardianStone": 110.0,
            "jewelry": 10.0
        },
        "chaosCheck": 0,
        "chaosGauge": 0,
        "chaosGold": 553.68,
        "guardianName": null,
        "guardian": {
            "id": 15,
            "category": "가디언토벌",
            "name": "소나벨",
            "level": 1580.0,
            "shilling": 0.0,
            "honorShard": 0.0,
            "leapStone": 8.0,
            "destructionStone": 66.3,
            "guardianStone": 199.7,
            "jewelry": 0.0
        },
        "guardianCheck": 0,
        "guardianGauge": 100,
        "guardianGold": 891.98,
        "eponaCheck": 0,
        "eponaGauge": 100,
        "todoList": [
            {
                "id": 156039,
                "name": "카양겔<br />하드 1 2 3",
                "gold": 6500,
                "check": false,
                "message": null,
                "currentGate": 0,
                "totalGate": 3,
                "weekCategory": "카양겔",
                "weekContentCategory": "하드",
                "sortNumber": 1,
                "goldCheck": true
            },
            {
                "id": 55964,
                "name": "일리아칸<br />노말 1 2 3",
                "gold": 7500,
                "check": false,
                "message": null,
                "currentGate": 0,
                "totalGate": 3,
                "weekCategory": "일리아칸",
                "weekContentCategory": "노말",
                "sortNumber": 2,
                "goldCheck": true
            },
            {
                "id": 409308,
                "name": "아브렐슈드<br />하드 1 2 3",
                "gold": 6000,
                "check": false,
                "message": null,
                "currentGate": 0,
                "totalGate": 3,
                "weekCategory": "아브렐슈드",
                "weekContentCategory": "하드",
                "sortNumber": 999,
                "goldCheck": true
            }
        ],
        "goldCharacter": true,
        "challengeGuardian": false,
        "challengeAbyss": false,
        "settings": {
            "showCharacter": true,
            "showEpona": false,
            "showChaos": true,
            "showGuardian": true,
            "showWeekTodo": true,
            "showWeekEpona": true,
            "showSilmaelChange": false,
            "showCubeTicket": true,
            "goldCheckVersion": false
        },
        "weekGold": 0,
        "weekEpona": 0,
        "silmaelChange": false,
        "cubeTicket": 0
    },
    {
        "id": 164,
        "characterClassName": "도화가",
        "characterImage": "https://img.lostark.co.kr/armory/9/7bfeb42775df8ef36b5eda7849126f5bd2f67b54a08627f9ce2df68e4069bc58.png?v=20240215130656",
        "characterName": "서예볼링",
        "itemLevel": 1590.0,
        "serverName": "루페온",
        "sortNumber": 3,
        "chaosName": null,
        "chaos": {
            "id": 8,
            "category": "카오스던전",
            "name": "천공1",
            "level": 1580.0,
            "shilling": 80164.0,
            "honorShard": 9913.0,
            "leapStone": 3.1,
            "destructionStone": 39.9,
            "guardianStone": 110.0,
            "jewelry": 10.0
        },
        "chaosCheck": 0,
        "chaosGauge": 0,
        "chaosGold": 553.68,
        "guardianName": null,
        "guardian": {
            "id": 15,
            "category": "가디언토벌",
            "name": "소나벨",
            "level": 1580.0,
            "shilling": 0.0,
            "honorShard": 0.0,
            "leapStone": 8.0,
            "destructionStone": 66.3,
            "guardianStone": 199.7,
            "jewelry": 0.0
        },
        "guardianCheck": 0,
        "guardianGauge": 100,
        "guardianGold": 891.98,
        "eponaCheck": 0,
        "eponaGauge": 100,
        "todoList": [
            {
                "id": 3193,
                "name": "카양겔<br />하드 1 2 3",
                "gold": 6500,
                "check": false,
                "message": null,
                "currentGate": 0,
                "totalGate": 3,
                "weekCategory": "카양겔",
                "weekContentCategory": "하드",
                "sortNumber": 1,
                "goldCheck": true
            },
            {
                "id": 3196,
                "name": "일리아칸<br />노말 1 2 3",
                "gold": 7500,
                "check": false,
                "message": null,
                "currentGate": 0,
                "totalGate": 3,
                "weekCategory": "일리아칸",
                "weekContentCategory": "노말",
                "sortNumber": 2,
                "goldCheck": true
            },
            {
                "id": 3190,
                "name": "아브렐슈드<br />하드 1 2 노말 3",
                "gold": 5500,
                "check": false,
                "message": null,
                "currentGate": 0,
                "totalGate": 3,
                "weekCategory": "아브렐슈드",
                "weekContentCategory": "하드",
                "sortNumber": 3,
                "goldCheck": true
            }
        ],
        "goldCharacter": true,
        "challengeGuardian": false,
        "challengeAbyss": false,
        "settings": {
            "showCharacter": true,
            "showEpona": false,
            "showChaos": true,
            "showGuardian": true,
            "showWeekTodo": true,
            "showWeekEpona": true,
            "showSilmaelChange": false,
            "showCubeTicket": true,
            "goldCheckVersion": false
        },
        "weekGold": 0,
        "weekEpona": 0,
        "silmaelChange": false,
        "cubeTicket": 0
    },
    {
        "id": 162,
        "characterClassName": "워로드",
        "characterImage": "https://img.lostark.co.kr/armory/5/7c6123f9806870dce098a32f384d6cd693bf0162dee031b794963403c8442c9b.png?v=20240213092651",
        "characterName": "카카오볼링",
        "itemLevel": 1600.0,
        "serverName": "루페온",
        "sortNumber": 4,
        "chaosName": null,
        "chaos": {
            "id": 9,
            "category": "카오스던전",
            "name": "천공2",
            "level": 1600.0,
            "shilling": 84164.0,
            "honorShard": 10128.0,
            "leapStone": 4.0,
            "destructionStone": 45.0,
            "guardianStone": 128.9,
            "jewelry": 11.0
        },
        "chaosCheck": 0,
        "chaosGauge": 0,
        "chaosGold": 617.34,
        "guardianName": null,
        "guardian": {
            "id": 15,
            "category": "가디언토벌",
            "name": "소나벨",
            "level": 1580.0,
            "shilling": 0.0,
            "honorShard": 0.0,
            "leapStone": 8.0,
            "destructionStone": 66.3,
            "guardianStone": 199.7,
            "jewelry": 0.0
        },
        "guardianCheck": 0,
        "guardianGauge": 100,
        "guardianGold": 891.98,
        "eponaCheck": 0,
        "eponaGauge": 100,
        "todoList": [
            {
                "id": 257258,
                "name": "카양겔<br />하드 1 2 3",
                "gold": 6500,
                "check": false,
                "message": null,
                "currentGate": 0,
                "totalGate": 3,
                "weekCategory": "카양겔",
                "weekContentCategory": "하드",
                "sortNumber": 1,
                "goldCheck": true
            },
            {
                "id": 156635,
                "name": "일리아칸<br />노말 1 2 3",
                "gold": 7500,
                "check": false,
                "message": null,
                "currentGate": 0,
                "totalGate": 3,
                "weekCategory": "일리아칸",
                "weekContentCategory": "노말",
                "sortNumber": 2,
                "goldCheck": true
            },
            {
                "id": 244433,
                "name": "상아탑<br />노말 1 2 3 4",
                "gold": 9000,
                "check": false,
                "message": null,
                "currentGate": 0,
                "totalGate": 4,
                "weekCategory": "상아탑",
                "weekContentCategory": "노말",
                "sortNumber": 3,
                "goldCheck": true
            }
        ],
        "goldCharacter": true,
        "challengeGuardian": false,
        "challengeAbyss": false,
        "settings": {
            "showCharacter": true,
            "showEpona": false,
            "showChaos": true,
            "showGuardian": true,
            "showWeekTodo": true,
            "showWeekEpona": true,
            "showSilmaelChange": false,
            "showCubeTicket": true,
            "goldCheckVersion": false
        },
        "weekGold": 0,
        "weekEpona": 0,
        "silmaelChange": false,
        "cubeTicket": 0
    },
    {
        "id": 43773,
        "characterClassName": "브레이커",
        "characterImage": "https://img.lostark.co.kr/armory/2/7b244c763db4689377a4c39423c64d3c4463a32bedb120cd745de4d2ab848660.png?v=20240211121618",
        "characterName": "원펀치볼링",
        "itemLevel": 1580.83,
        "serverName": "루페온",
        "sortNumber": 5,
        "chaosName": null,
        "chaos": {
            "id": 8,
            "category": "카오스던전",
            "name": "천공1",
            "level": 1580.0,
            "shilling": 80164.0,
            "honorShard": 9913.0,
            "leapStone": 3.1,
            "destructionStone": 39.9,
            "guardianStone": 110.0,
            "jewelry": 10.0
        },
        "chaosCheck": 0,
        "chaosGauge": 0,
        "chaosGold": 553.68,
        "guardianName": null,
        "guardian": {
            "id": 15,
            "category": "가디언토벌",
            "name": "소나벨",
            "level": 1580.0,
            "shilling": 0.0,
            "honorShard": 0.0,
            "leapStone": 8.0,
            "destructionStone": 66.3,
            "guardianStone": 199.7,
            "jewelry": 0.0
        },
        "guardianCheck": 0,
        "guardianGauge": 100,
        "guardianGold": 891.98,
        "eponaCheck": 0,
        "eponaGauge": 100,
        "todoList": [
            {
                "id": 442668,
                "name": "카양겔<br />하드 1 2 3",
                "gold": 6500,
                "check": false,
                "message": null,
                "currentGate": 0,
                "totalGate": 3,
                "weekCategory": "카양겔",
                "weekContentCategory": "하드",
                "sortNumber": 1,
                "goldCheck": false
            },
            {
                "id": 273739,
                "name": "일리아칸<br />노말 1 2 3",
                "gold": 7500,
                "check": false,
                "message": null,
                "currentGate": 0,
                "totalGate": 3,
                "weekCategory": "일리아칸",
                "weekContentCategory": "노말",
                "sortNumber": 2,
                "goldCheck": true
            },
            {
                "id": 233653,
                "name": "아브렐슈드<br />하드 1 2 노말 3",
                "gold": 5500,
                "check": false,
                "message": null,
                "currentGate": 0,
                "totalGate": 3,
                "weekCategory": "아브렐슈드",
                "weekContentCategory": "하드",
                "sortNumber": 3,
                "goldCheck": true
            }
        ],
        "goldCharacter": true,
        "challengeGuardian": false,
        "challengeAbyss": false,
        "settings": {
            "showCharacter": true,
            "showEpona": false,
            "showChaos": true,
            "showGuardian": true,
            "showWeekTodo": true,
            "showWeekEpona": true,
            "showSilmaelChange": false,
            "showCubeTicket": true,
            "goldCheckVersion": false
        },
        "weekGold": 0,
        "weekEpona": 0,
        "silmaelChange": false,
        "cubeTicket": 3
    },
    {
        "id": 167,
        "characterClassName": "바드",
        "characterImage": "https://img.lostark.co.kr/armory/8/46ab28c9e17d3dbc8c2b29f12bbf0fe951059a2058e87aa6d0a04ec756710e75.png?v=20231224061710",
        "characterName": "바드볼링",
        "itemLevel": 1551.67,
        "serverName": "루페온",
        "sortNumber": 6,
        "chaosName": null,
        "chaos": {
            "id": 6,
            "category": "카오스던전",
            "name": "절망1",
            "level": 1540.0,
            "shilling": 81193.0,
            "honorShard": 8173.0,
            "leapStone": 4.8,
            "destructionStone": 71.6,
            "guardianStone": 207.7,
            "jewelry": 11.0
        },
        "chaosCheck": 0,
        "chaosGauge": 100,
        "chaosGold": 961.0,
        "guardianName": null,
        "guardian": {
            "id": 14,
            "category": "가디언토벌",
            "name": "하누마탄",
            "level": 1540.0,
            "shilling": 0.0,
            "honorShard": 0.0,
            "leapStone": 14.0,
            "destructionStone": 101.4,
            "guardianStone": 309.5,
            "jewelry": 0.0
        },
        "guardianCheck": 0,
        "guardianGauge": 100,
        "guardianGold": 290.74,
        "eponaCheck": 0,
        "eponaGauge": 100,
        "todoList": [],
        "goldCharacter": false,
        "challengeGuardian": false,
        "challengeAbyss": false,
        "settings": {
            "showCharacter": true,
            "showEpona": false,
            "showChaos": true,
            "showGuardian": false,
            "showWeekTodo": true,
            "showWeekEpona": false,
            "showSilmaelChange": true,
            "showCubeTicket": true,
            "goldCheckVersion": false
        },
        "weekGold": 0,
        "weekEpona": 0,
        "silmaelChange": false,
        "cubeTicket": 11
    },
    {
        "id": 168,
        "characterClassName": "서머너",
        "characterImage": "https://img.lostark.co.kr/armory/5/a01bb0823d4a29209037171ce9cc20ce43761ded1e072b247c31cad2b4470b43.png?v=20240117103737",
        "characterName": "볼링치는개발자",
        "itemLevel": 1540.0,
        "serverName": "루페온",
        "sortNumber": 7,
        "chaosName": null,
        "chaos": {
            "id": 6,
            "category": "카오스던전",
            "name": "절망1",
            "level": 1540.0,
            "shilling": 81193.0,
            "honorShard": 8173.0,
            "leapStone": 4.8,
            "destructionStone": 71.6,
            "guardianStone": 207.7,
            "jewelry": 11.0
        },
        "chaosCheck": 0,
        "chaosGauge": 100,
        "chaosGold": 961.0,
        "guardianName": null,
        "guardian": {
            "id": 14,
            "category": "가디언토벌",
            "name": "하누마탄",
            "level": 1540.0,
            "shilling": 0.0,
            "honorShard": 0.0,
            "leapStone": 14.0,
            "destructionStone": 101.4,
            "guardianStone": 309.5,
            "jewelry": 0.0
        },
        "guardianCheck": 0,
        "guardianGauge": 100,
        "guardianGold": 290.74,
        "eponaCheck": 0,
        "eponaGauge": 100,
        "todoList": [],
        "goldCharacter": false,
        "challengeGuardian": false,
        "challengeAbyss": false,
        "settings": {
            "showCharacter": true,
            "showEpona": false,
            "showChaos": true,
            "showGuardian": false,
            "showWeekTodo": false,
            "showWeekEpona": false,
            "showSilmaelChange": true,
            "showCubeTicket": true,
            "goldCheckVersion": false
        },
        "weekGold": 0,
        "weekEpona": 0,
        "silmaelChange": false,
        "cubeTicket": 28
    },
    {
        "id": 166,
        "characterClassName": "배틀마스터",
        "characterImage": "https://img.lostark.co.kr/armory/8/ab4615a0fcfe1d180cd4c1e34be9598203b6dc924979cdb625c1d4eecbe20dfa.png?v=20240208230028",
        "characterName": "데이터볼링",
        "itemLevel": 1540.0,
        "serverName": "루페온",
        "sortNumber": 8,
        "chaosName": null,
        "chaos": {
            "id": 6,
            "category": "카오스던전",
            "name": "절망1",
            "level": 1540.0,
            "shilling": 81193.0,
            "honorShard": 8173.0,
            "leapStone": 4.8,
            "destructionStone": 71.6,
            "guardianStone": 207.7,
            "jewelry": 11.0
        },
        "chaosCheck": 0,
        "chaosGauge": 100,
        "chaosGold": 961.0,
        "guardianName": null,
        "guardian": {
            "id": 14,
            "category": "가디언토벌",
            "name": "하누마탄",
            "level": 1540.0,
            "shilling": 0.0,
            "honorShard": 0.0,
            "leapStone": 14.0,
            "destructionStone": 101.4,
            "guardianStone": 309.5,
            "jewelry": 0.0
        },
        "guardianCheck": 0,
        "guardianGauge": 100,
        "guardianGold": 290.74,
        "eponaCheck": 0,
        "eponaGauge": 100,
        "todoList": [],
        "goldCharacter": false,
        "challengeGuardian": false,
        "challengeAbyss": false,
        "settings": {
            "showCharacter": true,
            "showEpona": false,
            "showChaos": true,
            "showGuardian": false,
            "showWeekTodo": false,
            "showWeekEpona": false,
            "showSilmaelChange": true,
            "showCubeTicket": true,
            "goldCheckVersion": false
        },
        "weekGold": 0,
        "weekEpona": 0,
        "silmaelChange": false,
        "cubeTicket": 21
    },
    {
        "id": 169,
        "characterClassName": "데모닉",
        "characterImage": "https://img.lostark.co.kr/armory/1/74a2322713cba4d5d0866baeab9dd60797eaa70cbadc55f2fdf2ae5a1a1113ff.png?v=20240131120442",
        "characterName": "구글볼링",
        "itemLevel": 1540.0,
        "serverName": "루페온",
        "sortNumber": 9,
        "chaosName": null,
        "chaos": {
            "id": 6,
            "category": "카오스던전",
            "name": "절망1",
            "level": 1540.0,
            "shilling": 81193.0,
            "honorShard": 8173.0,
            "leapStone": 4.8,
            "destructionStone": 71.6,
            "guardianStone": 207.7,
            "jewelry": 11.0
        },
        "chaosCheck": 0,
        "chaosGauge": 100,
        "chaosGold": 961.0,
        "guardianName": null,
        "guardian": {
            "id": 14,
            "category": "가디언토벌",
            "name": "하누마탄",
            "level": 1540.0,
            "shilling": 0.0,
            "honorShard": 0.0,
            "leapStone": 14.0,
            "destructionStone": 101.4,
            "guardianStone": 309.5,
            "jewelry": 0.0
        },
        "guardianCheck": 0,
        "guardianGauge": 100,
        "guardianGold": 290.74,
        "eponaCheck": 0,
        "eponaGauge": 100,
        "todoList": [],
        "goldCharacter": false,
        "challengeGuardian": false,
        "challengeAbyss": false,
        "settings": {
            "showCharacter": true,
            "showEpona": false,
            "showChaos": true,
            "showGuardian": false,
            "showWeekTodo": false,
            "showWeekEpona": false,
            "showSilmaelChange": true,
            "showCubeTicket": true,
            "goldCheckVersion": false
        },
        "weekGold": 0,
        "weekEpona": 0,
        "silmaelChange": false,
        "cubeTicket": 24
    },
    {
        "id": 171,
        "characterClassName": "기상술사",
        "characterImage": "https://img.lostark.co.kr/armory/8/ac96f1b7aa0538cdb843d6d930ba82ec4138c36059b52dbe90c05eca59944e80.png?v=20231117103502",
        "characterName": "밤볼링",
        "itemLevel": 1500.0,
        "serverName": "루페온",
        "sortNumber": 10,
        "chaosName": null,
        "chaos": {
            "id": 4,
            "category": "카오스던전",
            "name": "공허1",
            "level": 1490.0,
            "shilling": 76884.0,
            "honorShard": 5416.0,
            "leapStone": 3.1,
            "destructionStone": 50.4,
            "guardianStone": 149.9,
            "jewelry": 8.0
        },
        "chaosCheck": 0,
        "chaosGauge": 100,
        "chaosGold": 696.44,
        "guardianName": null,
        "guardian": {
            "id": 13,
            "category": "가디언토벌",
            "name": "칼엘리고스",
            "level": 1490.0,
            "shilling": 0.0,
            "honorShard": 0.0,
            "leapStone": 10.1,
            "destructionStone": 74.3,
            "guardianStone": 222.6,
            "jewelry": 0.0
        },
        "guardianCheck": 0,
        "guardianGauge": 100,
        "guardianGold": 210.3,
        "eponaCheck": 0,
        "eponaGauge": 100,
        "todoList": [],
        "goldCharacter": false,
        "challengeGuardian": false,
        "challengeAbyss": false,
        "settings": {
            "showCharacter": true,
            "showEpona": false,
            "showChaos": true,
            "showGuardian": false,
            "showWeekTodo": false,
            "showWeekEpona": false,
            "showSilmaelChange": true,
            "showCubeTicket": true,
            "goldCheckVersion": false
        },
        "weekGold": 0,
        "weekEpona": 0,
        "silmaelChange": false,
        "cubeTicket": 39
    },
    {
        "id": 170,
        "characterClassName": "호크아이",
        "characterImage": "https://img.lostark.co.kr/armory/9/babbec0744553f44b601159211a5660b846b3d55e1d0d1e919b0de0b50947cfd.png?v=20240207101107",
        "characterName": "볼링이",
        "itemLevel": 1525.0,
        "serverName": "루페온",
        "sortNumber": 11,
        "chaosName": null,
        "chaos": {
            "id": 5,
            "category": "카오스던전",
            "name": "공허2",
            "level": 1520.0,
            "shilling": 77565.0,
            "honorShard": 6885.0,
            "leapStone": 4.1,
            "destructionStone": 60.8,
            "guardianStone": 243.4,
            "jewelry": 10.0
        },
        "chaosCheck": 0,
        "chaosGauge": 100,
        "chaosGold": 890.32,
        "guardianName": null,
        "guardian": {
            "id": 13,
            "category": "가디언토벌",
            "name": "칼엘리고스",
            "level": 1490.0,
            "shilling": 0.0,
            "honorShard": 0.0,
            "leapStone": 10.1,
            "destructionStone": 74.3,
            "guardianStone": 222.6,
            "jewelry": 0.0
        },
        "guardianCheck": 0,
        "guardianGauge": 100,
        "guardianGold": 210.3,
        "eponaCheck": 0,
        "eponaGauge": 100,
        "todoList": [],
        "goldCharacter": false,
        "challengeGuardian": false,
        "challengeAbyss": false,
        "settings": {
            "showCharacter": true,
            "showEpona": false,
            "showChaos": true,
            "showGuardian": false,
            "showWeekTodo": false,
            "showWeekEpona": false,
            "showSilmaelChange": true,
            "showCubeTicket": true,
            "goldCheckVersion": false
        },
        "weekGold": 0,
        "weekEpona": 0,
        "silmaelChange": false,
        "cubeTicket": 29
    },
    {
        "id": 172,
        "characterClassName": "창술사",
        "characterImage": "https://img.lostark.co.kr/armory/5/b40724116272fa569efef767127398a863e0bf41d2c33fe9ac5d16e840a23590.png?v=20231114052315",
        "characterName": "창술볼링",
        "itemLevel": 1490.0,
        "serverName": "루페온",
        "sortNumber": 13,
        "chaosName": null,
        "chaos": {
            "id": 4,
            "category": "카오스던전",
            "name": "공허1",
            "level": 1490.0,
            "shilling": 76884.0,
            "honorShard": 5416.0,
            "leapStone": 3.1,
            "destructionStone": 50.4,
            "guardianStone": 149.9,
            "jewelry": 8.0
        },
        "chaosCheck": 0,
        "chaosGauge": 100,
        "chaosGold": 696.44,
        "guardianName": null,
        "guardian": {
            "id": 13,
            "category": "가디언토벌",
            "name": "칼엘리고스",
            "level": 1490.0,
            "shilling": 0.0,
            "honorShard": 0.0,
            "leapStone": 10.1,
            "destructionStone": 74.3,
            "guardianStone": 222.6,
            "jewelry": 0.0
        },
        "guardianCheck": 0,
        "guardianGauge": 100,
        "guardianGold": 210.3,
        "eponaCheck": 0,
        "eponaGauge": 100,
        "todoList": [],
        "goldCharacter": false,
        "challengeGuardian": false,
        "challengeAbyss": false,
        "settings": {
            "showCharacter": true,
            "showEpona": false,
            "showChaos": true,
            "showGuardian": false,
            "showWeekTodo": false,
            "showWeekEpona": false,
            "showSilmaelChange": true,
            "showCubeTicket": true,
            "goldCheckVersion": false
        },
        "weekGold": 0,
        "weekEpona": 0,
        "silmaelChange": false,
        "cubeTicket": 19
    },
    {
        "id": 173,
        "characterClassName": "스트라이커",
        "characterImage": "https://img.lostark.co.kr/armory/3/153535f4b688e4415799d4cf41ab50dc75e9c586ee504e76b9dd35cd4d165607.png?v=20231229174906",
        "characterName": "넷마블볼링",
        "itemLevel": 1490.0,
        "serverName": "루페온",
        "sortNumber": 14,
        "chaosName": null,
        "chaos": {
            "id": 4,
            "category": "카오스던전",
            "name": "공허1",
            "level": 1490.0,
            "shilling": 76884.0,
            "honorShard": 5416.0,
            "leapStone": 3.1,
            "destructionStone": 50.4,
            "guardianStone": 149.9,
            "jewelry": 8.0
        },
        "chaosCheck": 0,
        "chaosGauge": 100,
        "chaosGold": 696.44,
        "guardianName": null,
        "guardian": {
            "id": 13,
            "category": "가디언토벌",
            "name": "칼엘리고스",
            "level": 1490.0,
            "shilling": 0.0,
            "honorShard": 0.0,
            "leapStone": 10.1,
            "destructionStone": 74.3,
            "guardianStone": 222.6,
            "jewelry": 0.0
        },
        "guardianCheck": 0,
        "guardianGauge": 100,
        "guardianGold": 210.3,
        "eponaCheck": 0,
        "eponaGauge": 100,
        "todoList": [],
        "goldCharacter": false,
        "challengeGuardian": false,
        "challengeAbyss": false,
        "settings": {
            "showCharacter": true,
            "showEpona": false,
            "showChaos": true,
            "showGuardian": false,
            "showWeekTodo": false,
            "showWeekEpona": false,
            "showSilmaelChange": true,
            "showCubeTicket": true,
            "goldCheckVersion": false
        },
        "weekGold": 0,
        "weekEpona": 0,
        "silmaelChange": false,
        "cubeTicket": 3
    },

];

export const RaidData = [
    {
        "name": "카멘",
        "count": 1,
        "totalCount": 1
    },
    {
        "name": "상아탑",
        "count": 1,
        "totalCount": 2
    },
    {
        "name": "일리아칸",
        "count": 1,
        "totalCount": 6
    },
    {
        "name": "카양겔",
        "count": 0,
        "totalCount": 5
    },
    {
        "name": "아브렐슈드",
        "count": 0,
        "totalCount": 4
    }
];